@startuml Certificado

[*] -> Anexado : Associado a\nrequisicao
Anexado --> AguardandoAnalise : Submissão\nda requisicao\ncom certificados
AguardandoAnalise -> RequisiçãoEmAnalise : Encaminhamento para\nCoordenação
RequisiçãoEmAnalise -> Recusado : Certificado recusado 
RequisiçãoEmAnalise -> Aceito : Certificado aceito
RequisiçãoEmAnalise -> ContagemDeHorasEmAnalise : Encaminhamento da Requisição\n com Certificado
ContagemDeHorasEmAnalise --> RequisiçãoEmAnalise : Contagem finalizada

@enduml